[wwb] Add torch_dtype = auto for gpt-oss (#3783)
<!-- Keep your pull requests (PRs) as atomic as possible. That increases
the likelihood that an individual PR won't be stuck because of adjacent
problems, merge conflicts, or code review.
Your merged PR is going to appear in the automatically generated release
notes on GitHub. So the clearer the title the better. -->
## Description
<!-- Please include a summary of the change. Also include relevant
motivation and context. -->

**Issue**:
This pull request resolves the following issue with gpt-oss-20b model:
<details>
  <summary>
gate_up = current_state @ self.gate_up_proj[expert_idx] +
self.gate_up_proj_bias[expert_idx]
RuntimeError: expected m1 and m2 to have the same dtype, but got: float
!= c10::BFloat16

  </summary>

```python
python whowhatbench/wwb.py --base-model openai/gpt-oss-20b --gt-data gt.csv --model-type text --hf

Evaluate pipeline:   0%|          | 0/26 [00:00<?, ?it/s]
 Traceback (most recent call last):
   File "./venv/bin/wwb", line 6, in <module>
     sys.exit(main())
              ^^^^^^
   File "./tools/who_what_benchmark/whowhatbench/wwb.py", line 1075, in main
     evaluator = create_evaluator(base_model, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./tools/who_what_benchmark/whowhatbench/wwb.py", line 752, in create_evaluator
     return EvaluatorCLS(
            ^^^^^^^^^^^^^
   File "./tools/who_what_benchmark/whowhatbench/text_evaluator.py", line 73, in __init__
     self.gt_data = self._generate_data(
                    ^^^^^^^^^^^^^^^^^^^^
   File "./tools/who_what_benchmark/whowhatbench/text_evaluator.py", line 200, in _generate_data
     gen_answer_fn(
   File "./tools/who_what_benchmark/whowhatbench/text_evaluator.py", line 165, in default_gen_answer
     tokens = model.generate(**inputs, do_sample=False, max_new_tokens=max_new_tokens, **get_ignore_parameters_flag())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/generation/utils.py", line 2566, in generate
     result = decoding_method(
              ^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/generation/utils.py", line 2786, in _sample
     outputs = self(**model_inputs, return_dict=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/utils/generic.py", line 918, in wrapper
     output = func(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/models/gpt_oss/modeling_gpt_oss.py", line 668, in forward
     outputs: MoeModelOutputWithPast = self.model(
                                       ^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/utils/generic.py", line 1072, in wrapper
     outputs = func(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/models/gpt_oss/modeling_gpt_oss.py", line 507, in forward
     hidden_states = decoder_layer(
                     ^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/modeling_layers.py", line 94, in __call__
     return super().__call__(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/models/gpt_oss/modeling_gpt_oss.py", line 386, in forward
     hidden_states, _ = self.mlp(hidden_states)  # diff with llama: router scores
                        ^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/models/gpt_oss/modeling_gpt_oss.py", line 170, in forward
     routed_out = self.experts(hidden_states, router_indices=router_indices, routing_weights=router_scores)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1790, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "./venv/lib/python3.12/site-packages/transformers/models/gpt_oss/modeling_gpt_oss.py", line 117, in forward
     gate_up = current_state @ self.gate_up_proj[expert_idx] + self.gate_up_proj_bias[expert_idx]
               ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 RuntimeError: expected m1 and m2 to have the same dtype, but got: float != c10::BFloat16
```
</details>

**Investigation**:
I see that the tensors are in different types, so they can't be
multiplied:
```python
gate_up = current_state @ self.gate_up_proj[expert_idx] + self.gate_up_proj_bias[expert_idx]
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: expected m1 and m2 to have the same dtype, but got: float != c10::BFloat16

(Pdb) current_state
tensor([[...]])

(Pdb) self.gate_up_proj[expert_idx]
tensor([[...]],
dtype=torch.bfloat16, requires_grad=True)

(Pdb) self.gate_up_proj_bias[expert_idx]
tensor([...],
requires_grad=True)
```

As far as I understand, the weights were dequantized from mxfp4
(https://huggingface.co/openai/gpt-oss-20b/blob/main/config.json#L57) to
bfloat16
(https://github.com/huggingface/transformers/blob/727741f533b1f47120db47ef5934296d07214d7e/src/transformers/integrations/mxfp4.py#L283).

The bias wasn't affected because it's in the exceptions
(https://github.com/huggingface/transformers/blob/727741f533b1f47120db47ef5934296d07214d7e/src/transformers/integrations/mxfp4.py#L283).

And current_state wasn't affected because it's in the exceptions in the
config
(https://huggingface.co/openai/gpt-oss-20b/blob/main/config.json#L52).

The tensors that weren't affected by quantization were cast by the
default to float32 in model_loaders
https://github.com/openvinotoolkit/openvino.genai/blob/4a3680a3fa4223470cd456c04cd903d216e0fa97/tools/who_what_benchmark/whowhatbench/model_loaders.py#L45,

https://github.com/openvinotoolkit/openvino.genai/blob/4a3680a3fa4223470cd456c04cd903d216e0fa97/tools/who_what_benchmark/whowhatbench/model_loaders.py#L191

**Fix**:
Suggesting to add a workaround for gpt-oss model with torch_dtypes =
'auto' instead
(https://huggingface.co/transformers/v4.10.1/main_classes/model.html).

I've tested that changes fixed the issue locally:
```python
python whowhatbench/wwb.py --base-model openai/gpt-oss-20b --gt-data gt.csv --model-type text --hf -v
Multiple distributions found for package optimum. Picked distribution: optimum
INFO:__main__:openvino runtime version: 2026.1.0-21367-63e31528c62-releases/2026/1
INFO:whowhatbench.model_loaders:Using HF Transformers API
Evaluate pipeline: 100%|████████████████████████████████████████████████████████████████| 27/27 [12:17<00:00, 27.32s/it]
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
```

And run pre-commit just in case:
```python
tools/who_what_benchmark/whowhatbench/model_loaders.py

trim trailing whitespace.............................(no files to check)Skipped
fix end of files.........................................................Passed
check for merge conflicts................................................Passed
check for case conflicts.................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect private key.......................................................Passed
mixed line ending........................................................Passed
check python ast.........................................................Passed
check yaml...........................................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check for added large files..............................................Passed
darker...................................................................Passed
```

I didn't add the new tests for the case as I recon it is third party
model and it should be evaluated in end-to-end tests, not in unit ones.

Feel free to suggest any imrpovements to the PR.

## Checklist:
- [x] This PR follows [GenAI Contributing
guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing).
<!-- Always follow them. If there are deviations, explain what and why.
-->
<!-- - [ ] Tests have been updated or added to cover the new code.
--><!-- Specify exactly which tests were added or updated. If the change
isn't maintenance related, update the tests at
https://github.com/openvinotoolkit/openvino.genai/tree/master/tests or
explain in the description why the tests don't need an update. -->
<!--- - [ ] This PR fully addresses the ticket. --><!--- If not, explain
clearly what is covered and what is not. If follow-up pull requests are
needed, specify in the description. -->
<!--- - [ ] I have made corresponding changes to the documentation.
--><!-- Run
github.com/\<username>/openvino.genai/actions/workflows/deploy_gh_pages.yml
on your fork with your branch as a parameter to deploy a test version
with the updated content. Replace this comment with the link to the
built docs. If the documentation is updated in a separate PR, clearly
specify it. -->

---------

Co-authored-by: Sofya Balandina <sofya.balandina@intel.com>