[wwb] Force dtype float32 for models loaded with diffusers (#4016)
## Description
transformers load model in "auto" model type depending on the data type
in HuggingFace, diffusers is still force torch.float32 for models. As a
result, we have text_encoder(s) in torch.float16, and a transformer/vae
in torch.float32. When several models in pipeline has different type it
leads to error like this:
RuntimeError: mat1 and mat2 must have the same dtype, but got BFloat16
and Float

Let's cast all models to one type.

[CVS-189083](https://jira.devtools.intel.com/browse/CVS-189083)
[CVS-189081](https://jira.devtools.intel.com/browse/CVS-189081)

## Checklist:
- [x] This PR follows [GenAI Contributing
guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing).
<!-- Always follow them. If there are deviations, explain what and why.
-->
- [ ] Tests have been updated or added to cover the new code. <!--
Specify exactly which tests were added or updated. If the change isn't
maintenance related, update the tests at
https://github.com/openvinotoolkit/openvino.genai/tree/master/tests or
explain in the description why the tests don't need an update. -->
- [ ] This PR fully addresses the ticket. <!--- If not, explain clearly
what is covered and what is not. If follow-up pull requests are needed,
specify in the description. -->
- [ ] I have made corresponding changes to the documentation. <!-- Run
github.com/\<username>/openvino.genai/actions/workflows/deploy_gh_pages.yml
on your fork with your branch as a parameter to deploy a test version
with the updated content. Replace this comment with the link to the
built docs. If the documentation is updated in a separate PR, clearly
specify it. -->